trigger:
#- master

resources:
- repo: self

variables:
- name: appName
  value: tocgenerator

- name: tag
  value: $(Build.BuildNumber)

- name: repository
  value: $(dockerid)/$(appName)

- name: imageNameWithTag
  value: $(repository):$(tag)

- name: serverChartLocation
  value: /root/helm-chart-folder/toc

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: docker build and push
      inputs:
        containerRegistry: 'my_docker_hub'
        repository: '$(repository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: $(tag)
        addPipelineData: false

    - task: Bash@3
      displayName: tag image as latest and push
      inputs:
        targetType: 'inline'
        script: |
          docker tag $(imageNameWithTag) $(repository):latest

    - task: Docker@2
      displayName: push latest tagged image
      inputs:
        containerRegistry: 'my_docker_hub'
        repository: $(repository)
        command: 'push'
        tags: 'latest'
        addPipelineData: false

    - task: CopyFilesOverSSH@0
      displayName: copy helm chart to server
      inputs:
        sshEndpoint: 'aliyun 47.102.201.58'
        sourceFolder: 'kubernetes'
        contents: '**'
        targetFolder: $(serverChartLocation)
        readyTimeout: '20000'
  
    - task: SSH@0
      displayName: run deploy shell on server
      inputs:
        sshEndpoint: 'aliyun 47.102.201.58'
        runOptions: 'script'
        scriptPath: 'deploy.sh'
        args: '$(tag) $(serverChartLocation)'
        readyTimeout: '20000'

    # - task: SSH@0
    #   displayName: update k8s application image
    #   inputs:
    #     sshEndpoint: 'aliyun 47.102.201.58'
    #     runOptions: 'inline'
    #     inline: 'kubectl set image deploy/tocgenerator-deploy $(appName)=$(imageNameWithTag)'
    #     readyTimeout: '20000'